name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: |
          **/**.go
          go.mod
          go.sum

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: lint 
      run: go vet ./...

    - name: Test
      run: go test -v ./...

    - name: Format 
      run: go fmt ./...

    - name: Build
      run: go build -v ./...
