name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - uses: actions/checkout@v3

    - uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: |
          **/**.go
          go.mod
          go.sum

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3

    - name: Test
      run: go test -v ./...

    - name: Format 
      run: go fmt ./...

    - name: Build
      run: go build -v ./...
